In [2]:
import numpy as np
l1=[1,2,3,4]
l1

[1, 2, 3, 4]

In [2]:
t1=(1,2,3,4)
t1

(1, 2, 3, 4)

In [3]:
a=np.array(l1) #creating a numpy array using np.array(object to be made array e.g. list,tuple etc.)
a

array([1, 2, 3, 4])

In [4]:
b=np.array(t1) #converting tuple into array.
t1

(1, 2, 3, 4)

In [6]:
type(b) #type of b is numpy array.


numpy.ndarray

In [7]:
type(a) #type of a is numpy array.

numpy.ndarray

In [8]:
type(t1) #t1 is tuple as initialised.

tuple

In [9]:
type(l1) #l1 is list as initialised.

list

In [10]:
a+2 #'+' adds the item after + operator to each item of array.

array([3, 4, 5, 6])

In [11]:
a*2#'*' multiplies the item after * operator to each item of array.

array([2, 4, 6, 8])

In [12]:
a-2 #'-' subtracts the item after - operator to each item of array.

array([-1,  0,  1,  2])

In [13]:
a/2 #'/' divides the item after / operator to each item of array.

array([0.5, 1. , 1.5, 2. ])

In [14]:
#Shape of array
c=np.array([1,2,3])
c.shape  #Gives the shape of array.

(3,)

In [15]:
#datatype of array
c.dtype #Gives datatype of array.

dtype('int32')

In [16]:
d=np.array([1.1,2.0,3.2])
d.dtype

dtype('float64')

In [17]:
a=np.array([(1,2,3),(4,5,6)])
a.shape

(2, 3)

In [18]:
a=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
a.shape

(1, 4, 3)

In [3]:
# Indexing and slicing
a=np.array([(1,2,3),(4,5,6)])
a
# First row 
a[0]
#second row
a[1]
a[1,2]  # a[1][2] element.
# Third column
a[:,2]

array([3, 6])

In [4]:
# Numpy ones()
np.ones((2,2)) #(2,2) is shape of array , default dtype is float64.
np.ones((1,2),dtype=np.int64) # Here we have mentioned dtype so output is in integer dtype.
np.ones((3,3))
np.ones((2,5),dtype=np.int16)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

In [5]:
# Numpy zeros()
np.zeros((2,2)) #(2,2) is shape of array , default dtype is float64.
np.zeros((2,2),dtype=np.int16) # Here we have mentioned dtype so output is in integer dtype.
np.zeros((2,3))
np.zeros((2,4),dtype=np.int64)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int64)

In [6]:
# Numpy arange()
np.arange(1,11) # we are making interval between 1-11 with default step i.e. 1
np.arange(1,15)
np.arange(1,8,2)  # we are making interval between 1-11 with default step i.e. 2.
np.arange(1,20,4)

array([ 1,  5,  9, 13, 17])

In [7]:
# Numpy arange()
a=np.matrix(np.ones((2,2)))
np.asarray(a)[1]=2 #The value of second row is changed to 2.
np.asarray(a)[1]=2 #The value of second row is changed to 2.

matrix([[1., 1.],
        [2., 2.]])

In [8]:
# Numpy flatten()
a=np.array([(1,2,3),(4,5,6)])
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [9]:
# Numpy reshape()
a=np.array([(1,2,3),(4,5,6)])
np.reshape(a,(3,2)) #reshape() the mentioned array to new shape.

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
# Numpy statistical functions.
a=np.random.normal(5,0.5,10)  #Creating an array of random numbers.
# Min 
np.min(a) #Minimum item of the above array.
# Max
np.max(a)  #Maximum item of the above array.
# Max
np.max(a)  #Maximum item of the above array.
# Mean
np.mean(a) #Mean of the items of the above array.
# Median
np.median(a) #Median of the items of the above array.
# Standard deviation
np.std(a)   #Standard deviation of items of the above array.

0.5063520200298126

In [11]:
# Numpy random.normal()
a=np.array([1,2,3])
randoM=np.random.normal(5,0.5,10) # If we plot ouput of this we will get a normal distribution or bell curve.
randoM

array([5.8314935 , 5.29973298, 5.0099573 , 4.21260886, 5.52710351,
       4.0884637 , 4.35820379, 5.04012183, 4.81932186, 5.24641146])

In [12]:
# Numpy hstack()
a=np.array([1,2,3,4]) 
b=np.array([5,6,7,8])
np.hstack((a,b))
np.hstack((b,a))

array([5, 6, 7, 8, 1, 2, 3, 4])

In [13]:
# Numpy vstack()
a=np.array([1,2,3,4]) 
b=np.array([5,6,7,8])
np.vstack((a,b))
np.vstack((a,a))
np.vstack((b,b))
np.vstack((b,a))


array([[5, 6, 7, 8],
       [1, 2, 3, 4]])